// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiveEpfXmkicpxhEsmkN5vp0LqLr0UuI',
    appId: '1:934563171285:web:a9cc8080c3a9cd70e94b5c',
    messagingSenderId: '934563171285',
    projectId: 'blood-donation-4e3b1',
    authDomain: 'blood-donation-4e3b1.firebaseapp.com',
    storageBucket: 'blood-donation-4e3b1.appspot.com',
    measurementId: 'G-JXM7V616CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWumXucR2XoEapTLNSAbgsHMtBWUlP6U',
    appId: '1:934563171285:android:4f7e4747532c1630e94b5c',
    messagingSenderId: '934563171285',
    projectId: 'blood-donation-4e3b1',
    storageBucket: 'blood-donation-4e3b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbceaRCHOX6kS2lEbltMkEm3fQMdFgXo',
    appId: '1:934563171285:ios:81bfa250c1ba298ae94b5c',
    messagingSenderId: '934563171285',
    projectId: 'blood-donation-4e3b1',
    storageBucket: 'blood-donation-4e3b1.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbceaRCHOX6kS2lEbltMkEm3fQMdFgXo',
    appId: '1:934563171285:ios:81bfa250c1ba298ae94b5c',
    messagingSenderId: '934563171285',
    projectId: 'blood-donation-4e3b1',
    storageBucket: 'blood-donation-4e3b1.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoiveEpfXmkicpxhEsmkN5vp0LqLr0UuI',
    appId: '1:934563171285:web:772d2c719dd9dd12e94b5c',
    messagingSenderId: '934563171285',
    projectId: 'blood-donation-4e3b1',
    authDomain: 'blood-donation-4e3b1.firebaseapp.com',
    storageBucket: 'blood-donation-4e3b1.appspot.com',
    measurementId: 'G-DLYMP8TRVY',
  );

}